# Generated by Django 5.1.7 on 2025-04-03 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enigma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=200, null=True)),
                ('testo', models.TextField(unique=True)),
                ('risposta_corretta', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(help_text="Data e ora di inizio visibilità dell'enigma")),
                ('end_time', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=False, help_text="Seleziona per rendere questo l'enigma corrente (assicurati che solo uno sia attivo!)")),
            ],
            options={
                'verbose_name': 'Enigma',
                'verbose_name_plural': 'Enigmi',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RispostaUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risposta_inserita', models.CharField(max_length=255)),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('is_corretta', models.BooleanField(default=False)),
                ('punteggio', models.FloatField(default=0.0, help_text='Punteggio da 0 a 10')),
                ('enigma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigmas.enigma')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risposta Utente',
                'verbose_name_plural': 'Risposte Utenti',
                'ordering': ['-data_inserimento'],
                'unique_together': {('utente', 'enigma')},
            },
        ),
    ]
