# Generated by Django 5.1.7 on 2025-07-29 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('icona', models.CharField(help_text="Es. 'bi bi-star'", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enigma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=200, null=True)),
                ('testo', models.TextField(help_text="La descrizione principale o l'introduzione all'enigma/caso.")),
                ('start_time', models.DateTimeField(help_text='Data e ora di inizio visibilità')),
                ('end_time', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=False, help_text="Seleziona per rendere questo l'enigma/caso corrente")),
                ('notifica_inviata', models.BooleanField(default=False, help_text='Indica se la notifica è già stata inviata')),
            ],
            options={
                'verbose_name': 'Enigma o Caso',
                'verbose_name_plural': 'Enigmi o Casi',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MessaggioEnigmista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampoRisposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(help_text="La domanda (es. 'Nome del colpevole')", max_length=255)),
                ('risposta_corretta', models.CharField(max_length=255)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione del campo nel form')),
                ('enigma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campi_risposta', to='enigmas.enigma')),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Un nome descrittivo per l'allegato.", max_length=100)),
                ('file', models.FileField(upload_to='allegati_enigmi/')),
                ('tipo_file', models.CharField(choices=[('IMG', 'Immagine'), ('VID', 'Video'), ('AUD', 'Audio'), ('DOC', 'Documento')], max_length=3)),
                ('enigma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='enigmas.enigma')),
            ],
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.CharField(max_length=255)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio_bonus', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RispostaUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_invio', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completa_corretta', models.BooleanField(default=False)),
                ('punteggio', models.FloatField(default=0.0)),
                ('suggerimenti_usati', models.PositiveIntegerField(default=0)),
                ('enigma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigmas.enigma')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_invio'],
                'unique_together': {('utente', 'enigma')},
            },
        ),
        migrations.CreateModel(
            name='RispostaUtenteMultipla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_inserito', models.CharField(max_length=255)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigmas.camporisposta')),
                ('risposta_generale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte_multiple', to='enigmas.rispostautente')),
            ],
        ),
        migrations.CreateModel(
            name='Suggerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('ordine', models.PositiveIntegerField(help_text="L'ordine in cui il suggerimento appare (1, 2, 3...)")),
                ('enigma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggerimenti', to='enigmas.enigma')),
            ],
            options={
                'ordering': ['ordine'],
                'unique_together': {('enigma', 'ordine')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ottenimento', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='enigmas.badge')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utente', 'badge')},
            },
        ),
    ]
