# Generated by Django 5.1.7 on 2025-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rispostautente',
            name='suggerimenti_usati',
        ),
        migrations.AddField(
            model_name='camporisposta',
            name='is_domanda_principale',
            field=models.BooleanField(default=False, help_text='Spunta questa casella se questa è la domanda principale che assegna il punteggio base.'),
        ),
    ]
