# Generated by Django 5.1.7 on 2025-04-05 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rispostautente',
            name='data_inserimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Suggerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(help_text='Il testo del suggerimento')),
                ('ordine', models.PositiveIntegerField(default=1, help_text='Ordine in cui mostrare i suggerimenti (1, 2, 3)')),
                ('enigma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggerimenti', to='enigmas.enigma')),
            ],
            options={
                'verbose_name': 'Suggerimento',
                'verbose_name_plural': 'Suggerimenti',
                'ordering': ['enigma', 'ordine'],
                'unique_together': {('enigma', 'ordine')},
            },
        ),
    ]
