# Generated by Django 5.1.7 on 2025-07-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifica',
            old_name='url',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='badge',
            name='icona',
            field=models.CharField(default='bi bi-patch-question', help_text="Es. 'bi bi-star'", max_length=50),
        ),
        migrations.DeleteModel(
            name='Suggerimento',
        ),
    ]
