# Generated by Django 5.1.7 on 2025-08-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0002_rename_url_notifica_link_alter_badge_icona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camporisposta',
            name='accetta_risposte_multiple',
            field=models.BooleanField(default=False, help_text='Spunta se questo campo può avere più risposte corrette (separate da virgola).'),
        ),
        migrations.AlterField(
            model_name='camporisposta',
            name='is_domanda_principale',
            field=models.BooleanField(default=False, help_text='Spunta se questa è la domanda principale.'),
        ),
        migrations.AlterField(
            model_name='camporisposta',
            name='risposta_corretta',
            field=models.CharField(help_text='Inserisci la risposta/le risposte corrette. Se accetti risposte multiple, separale con una virgola.', max_length=255),
        ),
    ]
