# Generated by Django 5.1.7 on 2025-04-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0002_alter_rispostautente_data_inserimento_suggerimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rispostautente',
            name='suggerimenti_usati',
            field=models.PositiveIntegerField(default=0, help_text='Numero di suggerimenti usati per questo enigma'),
        ),
        migrations.AlterField(
            model_name='rispostautente',
            name='punteggio',
            field=models.FloatField(default=0.0, help_text='Punteggio da 0 a 10 (con penalità hint)'),
        ),
    ]
