# Generated by Django 5.1.7 on 2025-08-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0003_camporisposta_accetta_risposte_multiple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camporisposta',
            name='accetta_risposte_multiple',
        ),
        migrations.RemoveField(
            model_name='camporisposta',
            name='risposta_corretta',
        ),
        migrations.AlterField(
            model_name='camporisposta',
            name='etichetta',
            field=models.CharField(help_text="La domanda (es. 'Chi è il colpevole?')", max_length=255),
        ),
        migrations.CreateModel(
            name='OpzioneRisposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(help_text="Il testo di una possibile risposta (es. 'Mario Rossi').", max_length=255)),
                ('is_corretta', models.BooleanField(default=False, help_text='Spunta se questa è una delle risposte corrette.')),
                ('campo_risposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opzioni', to='enigmas.camporisposta')),
            ],
        ),
    ]
