# Generated by Django 5.1.7 on 2025-08-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0004_remove_camporisposta_accetta_risposte_multiple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rispostautente',
            name='suggerimenti_usati',
            field=models.PositiveIntegerField(default=0, help_text='Numero di aiuti usati per questo enigma'),
        ),
        migrations.AlterField(
            model_name='camporisposta',
            name='etichetta',
            field=models.CharField(help_text="La domanda (es. 'Nome del colpevole')", max_length=255),
        ),
        migrations.AlterField(
            model_name='rispostautentemultipla',
            name='valore_inserito',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Suggerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(help_text="Il testo dell'aiuto")),
                ('ordine', models.PositiveIntegerField(default=1, help_text='Ordine in cui mostrare gli aiuti (1, 2, 3)')),
                ('enigma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggerimenti', to='enigmas.enigma')),
            ],
            options={
                'verbose_name': 'Aiuto',
                'verbose_name_plural': 'Aiuti',
                'ordering': ['enigma', 'ordine'],
                'unique_together': {('enigma', 'ordine')},
            },
        ),
    ]
