# Generated by Django 5.1.7 on 2025-04-06 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(help_text='Cosa bisogna fare per ottenere questo badge?')),
                ('rarita', models.CharField(choices=[('Comune', 'Comune'), ('Bronzo', 'Bronzo'), ('Argento', 'Argento'), ('Oro', 'Oro')], default='Bronzo', max_length=20)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ottenimento', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigmas.badge')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge Utente',
                'verbose_name_plural': 'Badges Utenti',
                'ordering': ['-data_ottenimento'],
                'unique_together': {('utente', 'badge')},
            },
        ),
    ]
