# Generated by Django 5.1.7 on 2025-04-06 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0005_badge_userbadge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(db_index=True, default=False)),
                ('tipo_notifica', models.CharField(choices=[('ENIGMA', 'Nuovo Enigma'), ('BADGE', 'Badge Ottenuto'), ('INFO', 'Generale')], default='INFO', max_length=10)),
                ('link', models.URLField(blank=True, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
