# Generated by Django 5.1.7 on 2025-04-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0006_notifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigma',
            name='notifica_inviata',
            field=models.BooleanField(default=False, help_text='Indica se la notifica per questo enigma è già stata inviata'),
        ),
    ]
