# Generated by Django 5.1.7 on 2025-04-06 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0007_enigma_notifica_inviata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessaggioEnigmista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, help_text='Titolo opzionale del messaggio', max_length=150, null=True)),
                ('testo', models.TextField(help_text='Il contenuto del messaggio (può contenere HTML di base se necessario)')),
                ('data_pubblicazione', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e ora in cui il messaggio diventa visibile')),
                ('pubblicato', models.BooleanField(db_index=True, default=True, help_text='Deseleziona per nascondere il messaggio senza cancellarlo')),
            ],
            options={
                'verbose_name': "Messaggio dell'Enigmista",
                'verbose_name_plural': "Messaggi dell'Enigmista",
                'ordering': ['-data_pubblicazione'],
            },
        ),
    ]
