# Generated by Django 5.1.7 on 2025-05-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0008_messaggioenigmista'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='punteggio_bonus',
            field=models.FloatField(default=0.0, help_text="Punti da aggiungere (positivi) o sottrarre (negativi) manualmente al punteggio totale dell'utente."),
        ),
    ]
